### ISSUE TITLE
Where does c.WriteTo come from?

### ISSUE THREAD

**Issue by m-kru** [mdlayher/ethernet#9]
In etherecho `c.WriteTo` function is used. https://github.com/mdlayher/ethernet/blob/529eae5b61181083b306246aa4c93f0761efa8a2/cmd/etherecho/main.go#L85  Where does this function come from?

**Comment by m-kru** [comment]
@mdlayher ping

**Comment by mdlayher** [comment]
See https://github.com/mdlayher/packet.
